//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
	using System.Data.Entity;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Account
    {
		[Required]
		[StringLength(50)]
		[Key]
		public string	Username { get; set; }

		[DataType(DataType.Password)]
		[Required]
        public string	Password { get; set; }
    }
}
