//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

    public partial class Bed
    {
        public Bed()
        {
            this.Visits = new HashSet<Visit>();
        }
    
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		[Display(Name= "Bed Id")]
        public int		Id { get; set; }

		[Display(Name= "Bed Name")]
		[StringLength(50)]
		[Required]
        public string	Name { get; set; }

		[DataType(DataType.Currency)]
		[Range(0.00, 10000.00)]
		[Display(Name= "Rate per Day")]
		[Required]
        public decimal		RatePerDay { get; set; }

		[Display(Name= "Bed Type")]
		[StringLength(50)]
		[Required]
        public string	Type { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
