//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

    public partial class Visit
    {
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		[Display(Name= "Visit Id")]
        public int	Id { get; set; }

		[Display(Name= "Patient Type")]
        public bool	PatientType { get; set; }

		public bool IsPay { get; set; }
		
		[Display(Name= "Patient Id")]
		[Required]
		public int	PatientId { get; set; }

		[Required]
		[Display(Name= "Doctor Id")]
        public int	DoctorId { get; set; }

		[Display(Name= "Bed Id")]
        public Nullable<int> BedId { get; set; }

		[DataType(DataType.DateTime)]
		[Display(Name= "Date of Visit")]
        public DateTime DateOfVisit { get; set; }

		[DataType(DataType.Date)]
		[Display(Name= "Date of Discharge")]
        public Nullable<DateTime> DateOfDischarge { get; set; }
        
		[StringLength(1000)]
		[Required]
		public string	Symptoms { get; set; }
        
		[StringLength(1000)]
		[Required]
		public string	Disease { get; set; }
        
		[StringLength(1000)]
		[Required]
		public string	Treatment { get; set; }
    
		[ForeignKey("BedId")]
        public virtual Bed Bed { get; set; }

		[ForeignKey("DoctorId")]
        public virtual Doctor Doctor { get; set; }

		[ForeignKey("PatientId")]
        public virtual Patient Patient { get; set; }
    }
}
